version: '3.9'
services:
  api:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '4000:4000'
    environment:
      - DB_TYPE=postgres
      - PG_USER=postgres
      - PG_PASSWORD=postgres
      - PG_DB=blog
      - PG_PORT=5432
      - PG_HOST=db
    develop:
      watch:
        - path: package.json
          action: rebuild
        - path: yarn.lock
          action: rebuild
        - path: .
          target: /app
          action: sync
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: blog
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: {}